In [2]:
import torch 
import torch.nn as nn 
import torch.nn.functional as F

In [3]:
torch.manual_seed(1)

In [4]:
#Data 
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [9]:
#model 선언 및 초기화. 단순 선형회귀이므로 input_dim = 1 , output_dim = 1
model = nn.Linear(1,1)
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.9414]], requires_grad=True), Parameter containing:
tensor([0.5997], requires_grad=True)]


In [10]:
optim = torch.optim.SGD(model.parameters(),lr=0.01)

In [11]:
epochs = 2000
for epoch in range(epochs +1 ): 
    prediction = model(x_train)
    loss = F.mse_loss(prediction,y_train)

    optim.zero_grad()
    loss.backward()
    optim.step()
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch,epochs,loss.item()))

Epoch    0/2000 Cost: 33.679783
Epoch  100/2000 Cost: 0.223159
Epoch  200/2000 Cost: 0.137899
Epoch  300/2000 Cost: 0.085213
Epoch  400/2000 Cost: 0.052656
Epoch  500/2000 Cost: 0.032539
Epoch  600/2000 Cost: 0.020107
Epoch  700/2000 Cost: 0.012425
Epoch  800/2000 Cost: 0.007678
Epoch  900/2000 Cost: 0.004744
Epoch 1000/2000 Cost: 0.002932
Epoch 1100/2000 Cost: 0.001812
Epoch 1200/2000 Cost: 0.001119
Epoch 1300/2000 Cost: 0.000692
Epoch 1400/2000 Cost: 0.000427
Epoch 1500/2000 Cost: 0.000264
Epoch 1600/2000 Cost: 0.000163
Epoch 1700/2000 Cost: 0.000101
Epoch 1800/2000 Cost: 0.000062
Epoch 1900/2000 Cost: 0.000039
Epoch 2000/2000 Cost: 0.000024


In [12]:
new_var = torch.FloatTensor([[4.0]])
pred_y = model(new_var)
print(pred_y)

tensor([[7.9902]], grad_fn=<AddmmBackward0>)


In [14]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9943]], requires_grad=True), Parameter containing:
tensor([0.0128], requires_grad=True)]


In [ ]:
#답 y = 2x 