In [1]:
import torch 
import torch.nn as nn 
import torch.nn.functional as F 
torch.manual_seed(1)

In [2]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])


In [3]:
model = nn.Linear(3,1)
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [4]:
optim = torch.optim.SGD(model.parameters(),lr=1e-5)

In [5]:
epochs = 2000
for epoch in range(epochs + 1):
    prediction = model(x_train)
    loss = F.mse_loss(prediction,y_train)
    optim.zero_grad()
    loss.backward()
    optim.step()
    print('Epoch {:4d}/{} Loss: {:.6f}'.format(
          epoch, epochs, loss.item()
      ))

Epoch    0/2000 Loss: 31667.599609
Epoch    1/2000 Loss: 9926.266602
Epoch    2/2000 Loss: 3111.513916
Epoch    3/2000 Loss: 975.451355
Epoch    4/2000 Loss: 305.908539
Epoch    5/2000 Loss: 96.042496
Epoch    6/2000 Loss: 30.260748
Epoch    7/2000 Loss: 9.641701
Epoch    8/2000 Loss: 3.178671
Epoch    9/2000 Loss: 1.152871
Epoch   10/2000 Loss: 0.517863
Epoch   11/2000 Loss: 0.318801
Epoch   12/2000 Loss: 0.256388
Epoch   13/2000 Loss: 0.236821
Epoch   14/2000 Loss: 0.230660
Epoch   15/2000 Loss: 0.228719
Epoch   16/2000 Loss: 0.228095
Epoch   17/2000 Loss: 0.227880
Epoch   18/2000 Loss: 0.227799
Epoch   19/2000 Loss: 0.227762
Epoch   20/2000 Loss: 0.227732
Epoch   21/2000 Loss: 0.227710
Epoch   22/2000 Loss: 0.227680
Epoch   23/2000 Loss: 0.227666
Epoch   24/2000 Loss: 0.227646
Epoch   25/2000 Loss: 0.227620
Epoch   26/2000 Loss: 0.227597
Epoch   27/2000 Loss: 0.227574
Epoch   28/2000 Loss: 0.227553
Epoch   29/2000 Loss: 0.227529
Epoch   30/2000 Loss: 0.227505
Epoch   31/2000 Loss: 0

In [7]:
new_var = torch.FloatTensor([[73,80,75]])
pred_y = model(new_var)
print(pred_y)

tensor([[151.2306]], grad_fn=<AddmmBackward0>)


In [8]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]


In [9]:
#모델을 class로 구현

In [10]:
model = nn.Linear(1,1)#단순선형회귀

In [13]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1,1)
    def forward(self,x):
        return self.linear(x)
model = LinearRegressionModel()

In [14]:
model = nn.Linear(3,1)#다중선형회귀

In [15]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3,1)

    def forward(self,x):
        return self.linear(x)
model = MultivariateLinearRegressionModel()