In [1]:
import numpy as np 

In [3]:
#0차원 tensor(scala)
d = np.array(5)
print("tensor의 차원 :",d.ndim)
print("tensor의 크기(shape) :",d.shape)

tensor의 차원 : 0
tensor의 크기(shape) : ()


In [4]:
#1차원 tensor(행렬)
d = np.array([1,2,3,4])
print("tensor의 차원 :",d.ndim)
print("tensor의 크기(shape) :",d.shape)

tensor의 차원 : 1
tensor의 크기(shape) : (4,)


In [7]:
#2차원 tensor(행렬)
d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("tensor의 차원 :",d.ndim)
print("tensor의 크기(shape) :",d.shape)

tensor의 차원 : 2
tensor의 크기(shape) : (3, 4)


In [12]:
#3차원 tensor(다차원배열)
d = np.array([
            [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], 
             [10, 11, 12, 13, 14]],[[15, 16, 17, 18, 19], 
            [19, 20, 21, 22, 23], [23, 24, 25, 26, 27]]
            ])
print("tensor의 차원 :",d.ndim)
print("tensor의 크기(shape) :",d.shape)

tensor의 차원 : 3
tensor의 크기(shape) : (2, 3, 5)


In [13]:
#vector와 metrix의 plus , minus 
A = np.array([8,4,5])
B = np.array([1,2,3])
print(A+B)
print(A-B)

[9 6 8]
[7 2 2]


In [14]:
#vector 내적 inner product
A = np.array([1,2,3])
B = np.array([4,5,6])
print(np.dot(A,B)) #1x4 + 2x5 +3x6 = 32

32


In [17]:
#행렬곱
A = np.array([[1,3],[2,4]])
B = np.array([[5,7],[6,8]])
print(np.matmul(A,B))

[[23 31]
 [34 46]]
